# Generated by Django 4.2 on 2026-01-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='numero',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
