# Generated by Django 4.2 on 2026-02-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
    ]
