# Generated by Django 4.2 on 2026-03-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_episodio_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='video',
            field=models.URLField(),
        ),
    ]
